### ISSUE TITLE
Combat dummy in Exile incorrect ID

### ISSUE THREAD

**Issue by 8bithooker** [crashf/DigitalHellPS#6]
### Description

Combat dummy in Exile incorrect ID

### SQL fix

```sql
UPDATE `world`.`creature` SET `id` = 174954, `map` = 2261, `zoneId` = 10424, `areaId` = 10639, `spawnDifficulties` = '0', `phaseUseFlags` = 0, `PhaseId` = 0, `PhaseGroup` = 0, `terrainSwapMap` = -1, `modelid` = 0, `equipment_id` = 0, `position_x` = -11.2698, `position_y` = 8.09454, `position_z` = 5.42378, `orientation` = 5.36703, `spawntimesecs` = 5, `spawndist` = 0, `currentwaypoint` = 0, `curhealth` = 114, `curmana` = 0, `MovementType` = 0, `npcflag` = 0, `unit_flags` = 0, `unit_flags2` = 0, `unit_flags3` = 0, `dynamicflags` = 0, `ScriptName` = '', `VerifiedBuild` = 41079 WHERE `guid` = 1050169;
UPDATE `world`.`creature` SET `id` = 174954, `map` = 2261, `zoneId` = 10424, `areaId` = 10639, `spawnDifficulties` = '0', `phaseUseFlags` = 0, `PhaseId` = 0, `PhaseGroup` = 0, `terrainSwapMap` = -1, `modelid` = 0, `equipment_id` = 0, `position_x` = -7.6347, `position_y` = 9.62948, `position_z` = 5.22708, `orientation` = 5.17507, `spawntimesecs` = 5, `spawndist` = 0, `currentwaypoint` = 0, `curhealth` = 114, `curmana` = 0, `MovementType` = 0, `npcflag` = 0, `unit_flags` = 0, `unit_flags2` = 0, `unit_flags3` = 0, `dynamicflags` = 0, `ScriptName` = '', `VerifiedBuild` = 41079 WHERE `guid` = 1050166;
UPDATE `world`.`creature` SET `id` = 174954, `map` = 2261, `zoneId` = 10424, `areaId` = 10639, `spawnDifficulties` = '0', `phaseUseFlags` = 0, `PhaseId` = 0, `PhaseGroup` = 0, `terrainSwapMap` = -1, `modelid` = 0, `equipment_id` = 0, `position_x` = -14.0159, `position_y` = 4.46932, `position_z` = 5.58979, `orientation` = 0, `spawntimesecs` = 5, `spawndist` = 0, `currentwaypoint` = 0, `curhealth` = 114, `curmana` = 0, `MovementType` = 0, `npcflag` = 0, `unit_flags` = 0, `unit_flags2` = 0, `unit_flags3` = 0, `dynamicflags` = 0, `ScriptName` = '', `VerifiedBuild` = 41079 WHERE `guid` = 1050165;
UPDATE `world`.`creature` SET `id` = 174954, `map` = 2261, `zoneId` = 10424, `areaId` = 10639, `spawnDifficulties` = '0', `phaseUseFlags` = 0, `PhaseId` = 0, `PhaseGroup` = 0, `terrainSwapMap` = -1, `modelid` = 0, `equipment_id` = 0, `position_x` = -11.1898, `position_y` = -7.82821, `position_z` = 5.42829, `orientation` = 0.674162, `spawntimesecs` = 5, `spawndist` = 0, `currentwaypoint` = 0, `curhealth` = 114, `curmana` = 0, `MovementType` = 0, `npcflag` = 0, `unit_flags` = 0, `unit_flags2` = 0, `unit_flags3` = 0, `dynamicflags` = 0, `ScriptName` = '', `VerifiedBuild` = 41079 WHERE `guid` = 1050164;
UPDATE `world`.`creature` SET `id` = 174954, `map` = 2261, `zoneId` = 10424, `areaId` = 10639, `spawnDifficulties` = '0', `phaseUseFlags` = 0, `PhaseId` = 0, `PhaseGroup` = 0, `terrainSwapMap` = -1, `modelid` = 0, `equipment_id` = 0, `position_x` = -7.825, `position_y` = -9.21034, `position_z` = 5.28981, `orientation` = 0.997226, `spawntimesecs` = 5, `spawndist` = 0, `currentwaypoint` = 0, `curhealth` = 114, `curmana` = 0, `MovementType` = 0, `npcflag` = 0, `unit_flags` = 0, `unit_flags2` = 0, `unit_flags3` = 0, `dynamicflags` = 0, `ScriptName` = '', `VerifiedBuild` = 41079 WHERE `guid` = 1050168;
UPDATE `world`.`creature` SET `id` = 174954, `map` = 2261, `zoneId` = 10424, `areaId` = 10639, `spawnDifficulties` = '0', `phaseUseFlags` = 0, `PhaseId` = 0, `PhaseGroup` = 0, `terrainSwapMap` = -1, `modelid` = 0, `equipment_id` = 0, `position_x` = -13.8277, `position_y` = -4.42007, `position_z` = 5.58518, `orientation` = 0, `spawntimesecs` = 5, `spawndist` = 0, `currentwaypoint` = 0, `curhealth` = 114, `curmana` = 0, `MovementType` = 0, `npcflag` = 0, `unit_flags` = 0, `unit_flags2` = 0, `unit_flags3` = 0, `dynamicflags` = 0, `ScriptName` = '', `VerifiedBuild` = 41079 WHERE `guid` = 1050167;
```

### Branch

master

### TC rev. hash/commit

@

**Comment by crashf** [comment]
Applied fix:

UPDATE `world`.`creature` SET `id` = 174954, `map` = 2261, `zoneId` = 10424, `areaId` = 10639, `spawnDifficulties` = '0', `phaseUseFlags` = 0, `PhaseId` = 0, `PhaseGroup` = 0, `terrainSwapMap` = -1, `modelid` = 0, `equipment_id` = 0, `position_x` = -11.2698, `position_y` = 8.09454, `position_z` = 5.42378, `orientation` = 5.36703, `spawntimesecs` = 5, `spawndist` = 0, `currentwaypoint` = 0, `curhealth` = 114, `curmana` = 0, `MovementType` = 0, `npcflag` = 0, `unit_flags` = 0, `unit_flags2` = 0, `unit_flags3` = 0, `dynamicflags` = 0, `ScriptName` = '', `VerifiedBuild` = 41079 WHERE `guid` = 1050169;
UPDATE `world`.`creature` SET `id` = 174954, `map` = 2261, `zoneId` = 10424, `areaId` = 10639, `spawnDifficulties` = '0', `phaseUseFlags` = 0, `PhaseId` = 0, `PhaseGroup` = 0, `terrainSwapMap` = -1, `modelid` = 0, `equipment_id` = 0, `position_x` = -7.825, `position_y` = -9.21034, `position_z` = 5.28981, `orientation` = 0.997226, `spawntimesecs` = 5, `spawndist` = 0, `currentwaypoint` = 0, `curhealth` = 114, `curmana` = 0, `MovementType` = 0, `npcflag` = 0, `unit_flags` = 0, `unit_flags2` = 0, `unit_flags3` = 0, `dynamicflags` = 0, `ScriptName` = '', `VerifiedBuild` = 41079 WHERE `guid` = 1050168;
UPDATE `world`.`creature` SET `id` = 174954, `map` = 2261, `zoneId` = 10424, `areaId` = 10639, `spawnDifficulties` = '0', `phaseUseFlags` = 0, `PhaseId` = 0, `PhaseGroup` = 0, `terrainSwapMap` = -1, `modelid` = 0, `equipment_id` = 0, `position_x` = -13.8277, `position_y` = -4.42007, `position_z` = 5.58518, `orientation` = 0, `spawntimesecs` = 5, `spawndist` = 0, `currentwaypoint` = 0, `curhealth` = 114, `curmana` = 0, `MovementType` = 0, `npcflag` = 0, `unit_flags` = 0, `unit_flags2` = 0, `unit_flags3` = 0, `dynamicflags` = 0, `ScriptName` = '', `VerifiedBuild` = 41079 WHERE `guid` = 1050167;
UPDATE `world`.`creature` SET `id` = 174954, `map` = 2261, `zoneId` = 10424, `areaId` = 10639, `spawnDifficulties` = '0', `phaseUseFlags` = 0, `PhaseId` = 0, `PhaseGroup` = 0, `terrainSwapMap` = -1, `modelid` = 0, `equipment_id` = 0, `position_x` = -7.6347, `position_y` = 9.62948, `position_z` = 5.22708, `orientation` = 5.17507, `spawntimesecs` = 5, `spawndist` = 0, `currentwaypoint` = 0, `curhealth` = 114, `curmana` = 0, `MovementType` = 0, `npcflag` = 0, `unit_flags` = 0, `unit_flags2` = 0, `unit_flags3` = 0, `dynamicflags` = 0, `ScriptName` = '', `VerifiedBuild` = 41079 WHERE `guid` = 1050166;
UPDATE `world`.`creature` SET `id` = 174954, `map` = 2261, `zoneId` = 10424, `areaId` = 10639, `spawnDifficulties` = '0', `phaseUseFlags` = 0, `PhaseId` = 0, `PhaseGroup` = 0, `terrainSwapMap` = -1, `modelid` = 0, `equipment_id` = 0, `position_x` = -11.1898, `position_y` = -7.82821, `position_z` = 5.42829, `orientation` = 0.674162, `spawntimesecs` = 5, `spawndist` = 0, `currentwaypoint` = 0, `curhealth` = 114, `curmana` = 0, `MovementType` = 0, `npcflag` = 0, `unit_flags` = 0, `unit_flags2` = 0, `unit_flags3` = 0, `dynamicflags` = 0, `ScriptName` = '', `VerifiedBuild` = 41079 WHERE `guid` = 1050164;
UPDATE `world`.`creature` SET `id` = 174954, `map` = 2261, `zoneId` = 10424, `areaId` = 10639, `spawnDifficulties` = '0', `phaseUseFlags` = 0, `PhaseId` = 0, `PhaseGroup` = 0, `terrainSwapMap` = -1, `modelid` = 0, `equipment_id` = 0, `position_x` = -14.0159, `position_y` = 4.46932, `position_z` = 5.58979, `orientation` = 0, `spawntimesecs` = 5, `spawndist` = 0, `currentwaypoint` = 0, `curhealth` = 114, `curmana` = 0, `MovementType` = 0, `npcflag` = 0, `unit_flags` = 0, `unit_flags2` = 0, `unit_flags3` = 0, `dynamicflags` = 0, `ScriptName` = '', `VerifiedBuild` = 41079 WHERE `guid` = 1050165;
